services:
  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3030:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"

  app:
    build: .
    init: true
    ports:
      - 8000:8000

volumes:
  grafana-storage:
